# Generated by Django 4.0.5 on 2022-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Number', models.IntegerField()),
                ('Amount_Paid', models.CharField(max_length=50)),
                ('Occupant_Name', models.CharField(max_length=50)),
                ('Occupant_Email', models.EmailField(max_length=300)),
                ('Occupants_Occupation', models.CharField(max_length=650)),
                ('Number_Of_Nights', models.CharField(max_length=650)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
    ]
