# Generated by Django 4.0.5 on 2022-06-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
