# Generated by Django 4.0.5 on 2022-06-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_records_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Kings_And_Queen_Hotel_Record',
        ),
    ]
