# Generated by Django 4.0.5 on 2022-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_record_kings_and_queen_hotel_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kings_And_Queen_Hotel_Record',
            new_name='Hotel_Record',
        ),
    ]
