# Generated by Django 4.0.5 on 2022-06-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_rename_kings_and_queen_hotel_record_hotel_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel_Record',
        ),
    ]
